@ControlOne.AdminService_HostAddress = http://localhost:55246

POST {{ControlOne.AdminService_HostAddress}}/admin/paymentorder
Content-Type: application/json
{
  "usuarioId": 136466,
  "eventoId": "1",
  "eventoFecha": "2026-04-28T13:48:34.451Z",
  "usuariosMayor4": 1,
  "usuariosMenor4": 2,
  "ticket3": 4,
  "ticket4": 0,
  "usuarioEmail": "jesusalvinoperu@gmail.com",
  "promociones": [
    2,
    2,
    2
  ],
  "token":''
}

###

POST {{ControlOne.AdminService_HostAddress}}/admin/addevento
Content-Type: application/json

{
  "id":"0",
  "lugar": "petroperu 4",
  "juego": "petro juego",
  "aforo": "5000",
  "fechaInicio": "2026-05-01",
  "operadorZona": "1000",
  "operadorJuego": "2000",
  "operadorZonaEmail": "operador_zona_pant_p@gmail.com",
  "operadorJuegoEmail": "operador_juego_pant_p@gmail.com",
  "password": "1234",
  "password2": "5678",
  "cajaInicial": "200",
  "tarifaMinutos": "30",
  "tarifaPrecioMinuto": "30",
  "tarifaPrecioMinutoAdicional": "1",
  "activo": 1,
  "ticketDefinicion": "TRIANGULO",
  "ticketsPromociones": "230|231",
  "horaInicio": "2000-01-31",
  "horaFinal": "2000-01-31",
  "descripcion": "Juego mecánico que desafía la destreza y equilibrio, ideal para jovenes y adultos",
  "inicio": "2026-05-01 11:00:00",
  "final": "2026-05-01 17:00:00",
  "isEntradaOnline": 1,
  "isCompraDirecta": 0,
  "promociones": [
    {
      "id": "0",
      "eventoId": "0",
      "promocionId": "11"
    },
    {
      "id": "0",
      "eventoId": "0",
      "promocionId": "13"
    }
  ]
}

### UPDATE EVENTO

  POST {{ControlOne.AdminService_HostAddress}}/admin/updateevento
Content-Type: application/json

{
  "id": "65",
  "lugar": "PETRO 4",
  "juego": "PETRO 4 JUEGO x",
  "aforo": "50",
  "fechaInicio": "2026-05-01T00:00:00.000Z",
  "operadorZonaEmail": "operador_zona_pant_p@gmail.com",
  "operadorJuegoEmail": "operador_juego_pant_p@gmail.com",
  "password": "1234",
  "password2": "5678",
  "cajaInicial": "200",
  "tarifaMinutos": "30",
  "tarifaPrecioMinuto": "30",
  "tarifaPrecioMinutoAdicional": "1",
  "activo": 1,
  "ticketDefinicion": "TRIANGULO",
  "ticketsPromociones": "",
  "horaInicio": "2000-02-01 10:30",
  "horaFinal": "2000-01-31 18:30",
  "descripcion": "Juego mecánico que desafía la destreza y equilibrio, ideal para jovenes y adultos",
  "inicio": "2026-05-01",
  "final": "2026-05-02",
  "isEntradaOnline": 1,
  "isCompraDirecta": 1,
  "promociones": [
    {
      "id": 0,
      "eventoId": "1",
      "promocionId": 231
    }
  ]
}

###

@usuarioId=136466
GET {{ControlOne.AdminService_HostAddress}}/admin/mistickets/{{usuarioId}}
